version: '3.7'
services:
  proxy:
    restart: always
    container_name: diego-socketio-nginx
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    links:
      - diego-socketio
  
  diego-socketio:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: diego-socketio
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/diego-socketio
    tty: true
    environment:
      PORT: 8080